# Generated by Django 5.1.2 on 2024-12-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
