site_name: Web-программирование
nav:
  - Home: index.md
  - Лаб №1: lab1.md
  - Лаб №2: lab2.md
  - Пр №3.1: pr3.md
  - Лаб №3:
    - Diet: lab3/diets.md
    - Breed: lab3/breeds.md
    - Hen: lab3/hens.md
    - Cage: lab3/cages.md
    - Workshop: lab3/workshops.md
theme:
  name: material